# SUSEP - Seguro Rural e Animal

- Base de dados: https://www.gov.br/susep/pt-br/central-de-conteudos/dados-estatisticos/bases-anonimizadas/bases_rural
- Inicio: 10/02/2026

---

# 1 - Importação das Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

---
# 2 - Reconhecimento dos Dados

## 2.1 - S_RURAL

In [ ]:
#Importação e leitura do CSV
df_original_s = pd.read_csv('S_RURAL_2021.csv', sep= ';')

#Leitura do head (5 primeiras linhas)
df_original_s.head()

,COD_APO,COD_ENDOSSO,COD_ITEM,DATA_COMP,COB_FUNDO,COD_MOD,ID_BEM,COBERTURA,CULTURA,MUNIC,UF,INDENIZ,DESP_SIN,EV_GER,VAL_FRANQ,D_AVISO,D_LIQ,D_OCORR_IN,D_OCORR_FI
0,292750154,4453571,7182988,2021,N,10,99,50,11310002.0,14955.0,RS,545.40,545.4,99,0.0,20210318,20210512,20210201,20210201
1,292750243,4453664,7183077,2021,N,10,99,50,11310002.0,44358.0,MT,257661.15,1847.9,99,0.0,20210111,20210705,20201022,20201022
2,292750361,4453786,7183195,2021,N,10,99,50,11310002.0,38735.0,RS,865.40,865.4,99,0.0,20210115,20210510,20210113,20210113
3,292750444,4453877,7183278,2021,N,10,99,50,11310002.0,46758.0,TO,382132.20,807.9,99,0.0,20210111,20210601,20201105,20201105
4,292750444,4453877,7183278,2021,N,10,99,999,11310002.0,46758.0,TO,2139.00,2139.0,99,0.0,20201120,20210126,20201105,20201105

In [6]:
#Informações do DF
df_original_s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158640 entries, 0 to 158639
Data columns (total 19 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   COD_APO      158640 non-null  int64
 1   COD_ENDOSSO  158640 non-null  int64
 2   COD_ITEM     158640 non-null  int64
 3   DATA_COMP    158640 non-null  int64
 4   COB_FUNDO    158640 non-null  object
 5   COD_MOD      158640 non-null  int64
 6   ID_BEM       158640 non-null  int64
 7   COBERTURA    158640 non-null  int64
 8   CULTURA      158640 non-null  float64
 9   MUNIC        158640 non-null  float64
 10  UF           158640 non-null  object
 11  INDENIZ      158640 non-null  float64
 12  DESP_SIN     158640 non-null  float64
 13  EV_GER       158640 non-null  int64
 14  VAL_FRANQ    158640 non-null  float64
 15  D_AVISO      158640 non-null  int64
 16  D_LIQ        158640 non-null  object
 17  D_OCORR_IN   158640 non-null  int64
 18  D_OCORR_FI   158640 non-null  int64
dtypes: float64(5), int64(11), object(3)
memory usage: 23.0+ MB

In [ ]:
#Contagem de valores nulos
df_original_s.isnull().sum()

COD_APO        0
COD_ENDOSSO    0
COD_ITEM       0
DATA_COMP      0
COB_FUNDO      0
COD_MOD        0
ID_BEM         0
COBERTURA      0
CULTURA        0
MUNIC          0
UF             0
INDENIZ        0
DESP_SIN       0
EV_GER         0
VAL_FRANQ      0
D_AVISO        0
D_LIQ          0
D_OCORR_IN     0
D_OCORR_FI     0
dtype: int64

In [7]:
#Analise descritiva dos dados (incluindo objects)
df_original_s.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
COD_APO,158640.0,NaN,NaN,NaN,292966264.105068,8003486.219233,34804490.0,289646528.75,293332037.0,296301996.0,309657429.0
COD_ENDOSSO,158640.0,NaN,NaN,NaN,5175815.452906,4057062.914169,107.0,439275.75,5525038.0,8315250.25,22487174.0
COD_ITEM,158640.0,NaN,NaN,NaN,8331856.715828,6851046.444326,52.0,898768.75,7957049.0,11058264.0,35274893.0
DATA_COMP,158640.0,NaN,NaN,NaN,2021.0,0.0,2021.0,2021.0,2021.0,2021.0,2021.0
COB_FUNDO,158640,2,N,112947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COD_MOD,158640.0,NaN,NaN,NaN,31.123411,26.918065,10.0,10.0,10.0,60.0,80.0
ID_BEM,158640.0,NaN,NaN,NaN,84.554759,20.255714,0.0,60.0,99.0,99.0,99.0
COBERTURA,158640.0,NaN,NaN,NaN,229.309657,364.157853,0.0,50.0,80.0,90.0,999.0
CULTURA,158640.0,NaN,NaN,NaN,51146068.044503,43999257.670366,11030227.0,11270805.0,12017280.0,99999999.0,99999999.0
MUNIC,158640.0,NaN,NaN,NaN,28549.494768,30759.738676,0.0,13561.0,27519.0,39844.0,431490.0
UF,158640,26,PR,61058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDENIZ,158640.0,NaN,NaN,NaN,31199.80598,192448.344046,-3069148.09,0.0,4326.05,24563.8075,59290622.0
DESP_SIN,158640.0,NaN,NaN,NaN,1611.885412,20991.966502,-69148.09,0.0,298.85,1050.6075,6220252.0
EV_GER,158640.0,NaN,NaN,NaN,22.915721,29.33832,0.0,8.0,8.0,27.0,99.0
VAL_FRANQ,158640.0,NaN,NaN,NaN,442.807209,10164.174669,0.0,0.0,0.0,0.0,1496710.03
D_AVISO,158640.0,NaN,NaN,NaN,20206760.389914,4713.400927,20120223.0,20201030.0,20210225.0,20210521.0,20220427.0
D_LIQ,158640,663,00000000,34864,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D_OCORR_IN,158640.0,NaN,NaN,NaN,20206348.742581,4774.429882,20120205.0,20201010.0,20210201.0,20210415.0,20220412.0
D_OCORR_FI,158640.0,NaN,NaN,NaN,20206348.742581,4774.429882,20120205.0,20201010.0,20210201.0,20210415.0,20220412.0

## 2.2 - R_RURAL

In [9]:
#Importação e leitura do CSV
df_original_r = pd.read_csv('R_RURAL_2021.csv', sep= ';')

#Leitura do head (5 primeiras linhas)
df_original_r.head()

,COD_APO,COD_ENDOSSO,COD_ITEM,DATA_COMP,COD_END,COB_FUNDO,COD_MOD,ID_BEM,COBERTURA,CULTURA,...,TIPO_FRANQ,VAL_FRANQ,AREA_SEG,IMP_SEG,PREMIO,PREMIO_SUB,ORIGEM_SUB,CORRETAGEM,PERC_CARR,PERC_DESC
0,292582168,4257666,6889891,2021,0,S,60,60,999,99999999.0,...,1,10.0,0.0,210000.0,452.94,0.0,00,7033.71,20.0,0.0
1,292582168,4257666,6889896,2021,0,S,60,60,100,99999999.0,...,1,10.0,0.0,450000.0,3535.82,0.0,00,7033.71,20.0,0.0
2,292582168,4257666,6889896,2021,0,S,60,60,999,99999999.0,...,1,10.0,0.0,90000.0,194.12,0.0,00,7033.71,20.0,0.0
3,292556275,4219017,6858237,2021,0,S,60,60,100,99999999.0,...,1,10.0,0.0,61500.0,1371.50,0.0,00,445.74,20.0,0.0
4,289707920,509905,1300765,2021,1,N,80,99,999,99999999.0,...,9,0.0,0.0,10220.0,5.49,0.0,00,1.65,0.0,0.0

In [10]:
#Informações do DF
df_original_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12773353 entries, 0 to 12773352
Data columns (total 24 columns):
 #   Column       Dtype
---  ------       -----
 0   COD_APO      int64
 1   COD_ENDOSSO  int64
 2   COD_ITEM     int64
 3   DATA_COMP    int64
 4   COD_END      int64
 5   COB_FUNDO    object
 6   COD_MOD      int64
 7   ID_BEM       int64
 8   COBERTURA    int64
 9   CULTURA      float64
 10  MUNIC        float64
 11  UF           object
 12  INICIO_VIG   int64
 13  FIM_VIG      int64
 14  TIPO_FRANQ   int64
 15  VAL_FRANQ    float64
 16  AREA_SEG     float64
 17  IMP_SEG      float64
 18  PREMIO       float64
 19  PREMIO_SUB   float64
 20  ORIGEM_SUB   object
 21  CORRETAGEM   float64
 22  PERC_CARR    float64
 23  PERC_DESC    float64
dtypes: float64(10), int64(11), object(3)
memory usage: 2.3+ GB

In [11]:
#Contagem de valores nulos
df_original_r.isnull().sum()

COD_APO        0
COD_ENDOSSO    0
COD_ITEM       0
DATA_COMP      0
COD_END        0
COB_FUNDO      0
COD_MOD        0
ID_BEM         0
COBERTURA      0
CULTURA        0
MUNIC          0
UF             0
INICIO_VIG     0
FIM_VIG        0
TIPO_FRANQ     0
VAL_FRANQ      0
AREA_SEG       0
IMP_SEG        0
PREMIO         0
PREMIO_SUB     0
ORIGEM_SUB     0
CORRETAGEM     0
PERC_CARR      0
PERC_DESC      0
dtype: int64

In [12]:
#Analise descritiva dos dados (incluindo objects)
df_original_r.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
COD_APO,12773353.0,NaN,NaN,NaN,293729913.237056,12344441.888311,30802257.0,292572219.0,296663320.0,296678543.0,309652154.0
COD_ENDOSSO,12773353.0,NaN,NaN,NaN,6216556.344155,3266592.149559,742.0,4242962.0,8597295.0,8639680.0,22473448.0
COD_ITEM,12773353.0,NaN,NaN,NaN,11358782.350603,6766485.065053,481.0,6877563.0,11525560.0,14474708.0,35246499.0
DATA_COMP,12773353.0,NaN,NaN,NaN,2021.0,0.0,2021.0,2021.0,2021.0,2021.0,2021.0
COD_END,12773353.0,NaN,NaN,NaN,0.221736,0.557953,0.0,0.0,0.0,0.0,4.0
COB_FUNDO,12773353,2,N,8338781,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COD_MOD,12773353.0,NaN,NaN,NaN,64.390779,20.66579,10.0,50.0,70.0,80.0,80.0
ID_BEM,12773353.0,NaN,NaN,NaN,80.293066,24.339394,10.0,60.0,99.0,99.0,99.0
COBERTURA,12773353.0,NaN,NaN,NaN,582.430949,454.769505,0.0,100.0,999.0,999.0,999.0
CULTURA,12773353.0,NaN,NaN,NaN,93993655.504573,22260166.951653,11005001.0,99999999.0,99999999.0,99999999.0,99999999.0
MUNIC,12773353.0,NaN,NaN,NaN,69376.390732,125658.819686,0.0,15710.0,28453.0,43287.0,999999.0
UF,12773353,28,RS,3662952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INICIO_VIG,12773353.0,NaN,NaN,NaN,20201100.613283,8744.717613,19000101.0,20200218.0,20200828.0,20210113.0,20290701.0
FIM_VIG,12773353.0,NaN,NaN,NaN,20209592.577587,7659.785512,20020630.0,20201130.0,20210518.0,20211107.0,22021105.0
TIPO_FRANQ,12773353.0,NaN,NaN,NaN,6.467118,2.952856,0.0,4.0,9.0,9.0,9.0
VAL_FRANQ,12773353.0,NaN,NaN,NaN,829932.214018,288070436.554208,-14280.0,0.0,0.0,0.0,99999999999.0
AREA_SEG,12773353.0,NaN,NaN,NaN,11.695231,5619.23472,0.0,0.0,0.0,0.0,7524000.0
IMP_SEG,12773353.0,NaN,NaN,NaN,115364.512589,1214666.79449,-50500000.0,10000.0,36000.0,100000.0,2600520000.0
PREMIO,12773353.0,NaN,NaN,NaN,1051.685467,20720.249411,-8690463.18,29.6,136.11,485.0,68405518.19
PREMIO_SUB,12773353.0,NaN,NaN,NaN,236.298213,3772.295001,-68497.85,0.0,0.0,0.0,255120.84
ORIGEM_SUB,12773353,5,00,12320013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CORRETAGEM,12773353.0,NaN,NaN,NaN,385.591844,395699.058228,-1298768.08,7.37,33.62,121.25,999999999.0
PERC_CARR,12773353.0,NaN,NaN,NaN,14.096609,11.932522,0.0,0.2,17.91,25.0,99.0
PERC_DESC,12773353.0,NaN,NaN,NaN,0.152531,6.240547,-1709.0,0.0,0.0,0.0,196.3

---
# 3 - Investigação dos Dados

- Identificar se as Bases contem informações distintas ou complementares

## 3.1 - Comparação de Colunas R x S

In [14]:
df_original_r.columns

Index(['COD_APO', 'COD_ENDOSSO', 'COD_ITEM', 'DATA_COMP', 'COD_END',
       'COB_FUNDO', 'COD_MOD', 'ID_BEM', 'COBERTURA', 'CULTURA', 'MUNIC', 'UF',
       'INICIO_VIG', 'FIM_VIG', 'TIPO_FRANQ', 'VAL_FRANQ', 'AREA_SEG',
       'IMP_SEG', 'PREMIO', 'PREMIO_SUB', 'ORIGEM_SUB', 'CORRETAGEM',
       'PERC_CARR', 'PERC_DESC'],
      dtype='object')

In [16]:
df_original_s.columns

Index(['COD_APO', 'COD_ENDOSSO', 'COD_ITEM', 'DATA_COMP', 'COB_FUNDO',
       'COD_MOD', 'ID_BEM', 'COBERTURA', 'CULTURA', 'MUNIC', 'UF', 'INDENIZ',
       'DESP_SIN', 'EV_GER', 'VAL_FRANQ', 'D_AVISO', 'D_LIQ', 'D_OCORR_IN',
       'D_OCORR_FI'],
      dtype='object')

## 3.2 - Join entre as bases

In [17]:
#Variavel com chaves primarias
chaves = ['COD_APO', 'COD_ENDOSSO', 'COD_ITEM']

#Left Join
df_join_lef = df_original_r.merge(
    df_original_s[chaves].drop_duplicates(),
    on=chaves,
    how='left',
    indicator=True
)

df_join_lef['_merge'].value_counts(normalize=True)

_merge
left_only     0.980393
both          0.019607
right_only    0.000000
Name: proportion, dtype: float64

Notas:

- maioria left_only → apólices sem sinistro 
- parte both → apólices com sinistros
- quase nenhum right_only → consistência

In [20]:
df_rural = df_original_r.copy()
df_sinistro = df_original_s.copy()

---
# 4 - Analise estatistica das Bases

## 4.1 - DF_RURAL